version: 2.1

executors:
  toolsdeps:
    docker:
      - image: circleci/clojure:openjdk-8-tools-deps
    working_directory: /home/circleci/replikativ

jobs:
  setup:
    executor: toolsdeps
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}
            - source-
      - checkout
      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git
      - restore_cache:
          keys:
            - deps-{{ checksum "deps.edn" }}
            - deps-
      - run: lein deps
      - save_cache:
          key: deps-{{ checksum "deps.edn" }}
          paths:
            - /home/circleci/.m2
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - .m2
            - replikativ

  unittest:
    executor: toolsdeps
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Run Unittests
          command: ./bin/kaocha
          no_output_timeout: 5m

          #integrationtest:
          #  executor: leiningen
          #  docker:
          #    - image: mopedtobias/cimg:1.10
          #    - image: circleci/postgres:11-alpine
          #      environment:
          #        POSTGRES_USER: alice
          #        POSTGRES_PASSWORD: foo
          #        POSTGRES_DB: config-test
          #  steps:
          #    - attach_workspace:
          #        at: /home/circleci
          #    - run:
          #        name: Run Integrationtests
          #        command: ./bin/run-integration-tests
          #        no_output_timeout: 5m

  build:
    executor: leiningen
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Build
          command: deps -A:depstar
          no_output_timeout: 5m

  deploy-snapshot:
    executor: leiningen
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          command: |
            VERSION=$(head -n 1 project.clj | awk '{print $3}' | tr -d \")
            if [[ ${VERSION} =~ .*-SNAPSHOT ]]; then
                lein deploy clojars
            else
                exit 0
            fi

  deploy-release:
    executor: leiningen
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Deploy Release to Clojars
          command: |
            VERSION=$(head -n 1 project.clj | awk '{print $3}' | tr -d \")
            if [[ ${VERSION} =~ .*-SNAPSHOT ]]; then
                exit 0
            else
                lein deploy clojars
            fi

workflows:
  build_test_and_deploy:
    jobs:
      - setup
      - unittest:
          requires:
            - setup
      - integrationtest:
          requires:
            - setup
      - build:
          requires:
            - setup
      - deploy-snapshot:
          filters:
            branches:
              only: development
          requires:
            - setup
            - unittest
            - integrationtest
            - build
      - deploy-release:
          filters:
            branches:
              only: master
          requires:
            - setup
            - unittest
            - integrationtest
            - build
